version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
    postgres:
      build: db
      ports:
        - "5432:5432"
    backend: #name of the second service
      build: backend # specify the directory of the Dockerfile
      ports:
        - "3000:3000" #specify ports forewarding
      depends_on:
      - postgres
    giggers-app: # name of the first service
      build: giggers-app # specify the directory of the Dockerfile
      ports:
        - "4200:4200" # specify port forewarding

